id: I02977F59
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:52:18+00:00'
last_modified: '2022-06-08T13:22:30.692275+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8185
  title: གྲུབ་པའི་རིག་འཛིན་ཆེན་པོ་རང་རིག་རྡོ་རྗེའི་གསུང་གཅེས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3300':
      image_group_id: I3CN8187
      title: ''
      total_pages: 449
      order: 1
      base_file: 3300.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
